Repository pagermon/pagermon, pull requests merged in 2019-03, with the labels that each got.

#222 Plugin - MessageRepeat
  server/plugins/MessageRepeat.js
  server/plugins/MessageRepeat.json
Labels: Plugins, enhancement

#239 Add's ability to select Icon Size on homepage
  CHANGELOG.md
  server/public/templates/admin/settings.html
  server/routes/index.js
  server/views/index.ejs
Labels: UI, enhancement

#240 Update repository URL
  CHANGELOG.md
  server/package.json
Labels: bug

#241 High Resolution Mobile Fix
  CHANGELOG.md
  server/views/index.ejs
Labels: UI, bug

#243 Better Docker support for server
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  server/Dockerfile
  server/entrypoint.sh
Labels: enhancement
