Repository pagermon/pagermon, pull requests merged in 2019-04, with the labels that each got.

#251 In which winston decides he does not have to follow the laws of time and space
  CHANGELOG.md
  server/log.js
Labels: bug

#253 Fix High Resolution Display Properly
  CHANGELOG.md
  server/public/stylesheets/style.css
  server/views/index.ejs
Labels: bug

#258 Gotify Plugin pagermon/pagermon#257
  CHANGELOG.md
  server/plugins/Gotify.js
  server/plugins/Gotify.json
Labels: Plugins, enhancement

#174 Support Multiple Databases
  .gitignore
  CHANGELOG.md
  README.md
  server/app.js
  server/config/default.json
  server/db.js
  server/knex/knex.js
  server/knex/migrations/20190322204646_create_capcodes_table.js
  server/knex/migrations/20190322204706_create_messages_table.js
  server/knex/migrations/20190322204710_create_indexes_triggers.js
  server/knex/migrations/20190425225205_sqlite_triggers.js
  server/knexfile.js
  server/package.json
  server/public/javascripts/admin/admin.main.js
  server/public/templates/admin/settings.html
  server/routes/api.js
Labels: DB, enhancement

#268 V0.3.0 Release
  .gitignore
  CHANGELOG.md
  README.md
  client/README.md
  client/config/default.json
  client/import.js
  client/package.json
  client/reader.js
  docker-compose.yml
  docker/Dockerfile
  server/Dockerfile
  server/app.js
  server/config/default.json
  server/db.js
  server/entrypoint.sh
  server/knex/knex.js
  server/knex/migrations/20190322204646_create_capcodes_table.js
  server/knex/migrations/20190322204706_create_messages_table.js
  server/knex/migrations/20190322204710_create_indexes_triggers.js
  server/knex/migrations/20190425225205_sqlite_triggers.js
  server/knexfile.js
  server/log.js
  server/package.json
  server/plugins/Gotify.js
  server/plugins/Gotify.json
  server/plugins/MessageRepeat.js
  server/plugins/MessageRepeat.json
  server/public/javascripts/admin/admin.main.js
  server/public/stylesheets/style.css
  server/public/templates/admin/settings.html
  server/routes/api.js
  server/routes/index.js
  server/views/global/footer.ejs
  server/views/index.ejs
Labels: RELEASE
