Repository pagermon/pagermon, pull requests merged in 2019-08, with the labels that each got.

#301 Optimize Duplicate checking queries
  CHANGELOG.md
  server/routes/api.js
Labels: DB, KNEX, bug

#304 Fix MessageRepeat error handling
  CHANGELOG.md
  server/plugins/MessageRepeat.js
Labels: Plugins, bug

#306 Add Azure Application Insight Support
  CHANGELOG.md
  server/app.js
  server/config/default.json
  server/package.json
  server/public/templates/admin/settings.html
Labels: enhancement

#308 Vulnerability Fix
  CHANGELOG.md
  server/routes/api.js
Labels: bug, vulnerability

#309 v0.3.4 Release
  CHANGELOG.md
  server/app.js
  server/config/default.json
  server/package.json
  server/plugins/MessageRepeat.js
  server/public/templates/admin/settings.html
  server/routes/api.js
Labels: RELEASE

#310 fix incorrect default false statement
  CHANGELOG.md
  server/config/default.json
Labels: bug

#311 Add knex logging to winston
  CHANGELOG.md
  server/knexfile.js
  server/log.js
Labels: KNEX, enhancement

#312 Add Google Analytics Support
  CHANGELOG.md
  server/config/default.json
  server/public/templates/admin/settings.html
  server/routes/index.js
  server/views/global/header-admin.ejs
  server/views/global/header.ejs
Labels: UI, enhancement

#313 Login Failed URL
  CHANGELOG.md
  server/routes/index.js
Labels: enhancement
