Repository pagermon/pagermon, pull requests merged in 2020-04, with the labels that each got.

#369 Add v4 Shims
  CHANGELOG.md
  server/views/global/header.ejs
Labels: bug

#372 Updated version oracledb to fix dockerbuild
  server/package.json
Labels: bug

#374 Docker: Disabled OracleDB for armhf build
  README.md
  server/Dockerfile.armhf
  server/hooks/build
  server/hooks/pre_build
Labels: bug

#370 In where the query builder does not execute the query builder because query builders cannot execute query builders
  CHANGELOG.md
  server/routes/api.js
Labels: KNEX, bug

#376 Docker: Fix for saving config in docker if changed UID,GID
  CHANGELOG.md
  server/Dockerfile
  server/Dockerfile.armhf
Labels: bug

#379 In which Pagermon/Collaborators gave up on FontAwesomev5
  CHANGELOG.md
  server/views/global/header.ejs
Labels: bug

#387 Improved docker docs
  CHANGELOG.md
  README.md
Labels: enhancement

#388 Fix button export button on mobile
  CHANGELOG.md
  server/themes/default/public/stylesheets/style.css
Labels: UI

#389 Implement FontAwesome5
  CHANGELOG.md
  server/themes/default/public/templates/admin/aliasDetails.html
  server/themes/default/views/global/header.ejs
Labels: UI
