Repository pagermon/pagermon, pull requests merged in 2020-05, with the labels that each got.

#392 Add CSV Import to capcodes
  CHANGELOG.md
  server/routes/api.js
  server/themes/default/public/javascripts/admin/admin.main.js
  server/themes/default/public/templates/admin/aliases.html
Labels: UI, enhancement

#395 Fix393
  CHANGELOG.md
  server/themes/default/views/global/header.ejs
  server/themes/default/views/global/menu.ejs
Labels: bug

#394 Release v0.3.8
  CHANGELOG.md
  README.md
  server/app.js
  server/config/default.json
  server/package.json
  server/routes/admin.js
  server/routes/api.js
  server/routes/index.js
  server/themes/default/public/android-chrome-192x192.png
  server/themes/default/public/android-chrome-512x512.png
  server/themes/default/public/apple-touch-icon.png
  server/themes/default/public/browserconfig.xml
  server/themes/default/public/favicon-16x16.png
  server/themes/default/public/favicon-32x32.png
  server/themes/default/public/favicon.ico
  server/themes/default/public/javascripts/admin/admin.main.js
  server/themes/default/public/javascripts/angular-highlight.js
  server/themes/default/public/javascripts/angular-highlight.min.js
  server/themes/default/public/javascripts/angular-textreplace.js
  server/themes/default/public/manifest.json
  server/themes/default/public/mstile-150x150.png
  server/themes/default/public/safari-pinned-tab.svg
  server/themes/default/public/stylesheets/style.css
  server/themes/default/public/stylesheets/textAngular.css
  server/themes/default/public/templates/admin/admin.html
  server/themes/default/public/templates/admin/aliasDetails.html
  server/themes/default/public/templates/admin/aliases.html
  server/themes/default/public/templates/admin/reset.html
  server/themes/default/public/templates/admin/settings.html
  server/themes/default/public/templates/popover.html
  server/themes/default/views/admin.ejs
  server/themes/default/views/global/error.ejs
  server/themes/default/views/global/footer.ejs
  server/themes/default/views/global/header-admin.ejs
  server/themes/default/views/global/header.ejs
  server/themes/default/views/global/menu.ejs
  server/themes/default/views/global/pagination.ejs
  server/themes/default/views/index.ejs
  server/themes/default/views/login.ejs
Labels: RELEASE

#397 Up max CSV Import Size
  CHANGELOG.md
  server/app.js
Labels: bug

#398 Various fixes
  server/app.js
  server/package.json
Labels: CLEANUP

#403 Fix Multi-Delete Capcodes on MYSQL
  CHANGELOG.md
  server/knex/migrations/20200507165756_messages_foreignkey_fix.js
Labels: DB, MySQL, bug

#401 Migrated plugins from request and http to axios client
  CHANGELOG.md
  server/package.json
  server/plugins/AdvancedWebhook.js
  server/plugins/Gotify.js
  server/plugins/Gotify.json
  server/plugins/MessageRepeat.js
  server/plugins/MicrosoftTeams.js
  server/plugins/SimpleWebhook.js
Labels: CLEANUP, Plugins, enhancement

#404 Fix delete button for Aliases
  CHANGELOG.md
  server/routes/api.js
  server/themes/default/public/javascripts/admin/admin.main.js
Labels: bug

#407 Fix Shell plugin - Missing Callback
  server/plugins/Shell.js
Labels: Plugins, bug

#405 Release v0.3.9
  CHANGELOG.md
  server/app.js
  server/knex/migrations/20200507165756_messages_foreignkey_fix.js
  server/package.json
  server/plugins/AdvancedWebhook.js
  server/plugins/Gotify.js
  server/plugins/Gotify.json
  server/plugins/MessageRepeat.js
  server/plugins/MicrosoftTeams.js
  server/plugins/Shell.js
  server/plugins/SimpleWebhook.js
  server/routes/api.js
  server/themes/default/public/javascripts/admin/admin.main.js
Labels: RELEASE
